version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: osticket-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h127.0.0.1 -uroot -p$${MARIADB_ROOT_PASSWORD} -e 'SELECT 1' >/dev/null 2>&1"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 60s

  osticket:
    image: tiredofit/osticket:latest
    container_name: osticket-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: ${MARIADB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASS: ${MARIADB_PASSWORD}
      INSTALL_SECRET: ${INSTALL_SECRET}
      ADMIN_FIRSTNAME: ${ADMIN_FIRSTNAME}
      ADMIN_LASTNAME: ${ADMIN_LASTNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      TIMEZONE: ${TIMEZONE}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      CONTAINER_ENABLE_MONITORING: ${CONTAINER_ENABLE_MONITORING}
      CONTAINER_ENABLE_MESSAGING: ${CONTAINER_ENABLE_MESSAGING}
    ports:
      - "8080:80"

volumes:
  db_data:
